from services.ai_service import is_live_mode_enabled, call_fireworks_api
from services.mock_service import get_mock_workflow
from services.prompt_templates import FINAL_OUTPUT_PROMPT
from services.trace_service import TraceService

def run_workflow(task: str) -> dict:
    """
    Orchestrates the NexusOps AI pipeline.
    Routes to mock or live execution based on environment config safely.
    """
    if not is_live_mode_enabled():
        return get_mock_workflow(task)
        
    try:
        # Generate live trace
        tracer = TraceService()
        tracer.add_trace("task_received", "completed", f"Received task: {task[:50]}...")
        
        # In the future, these would be discrete calls per agent using prompt_templates.
        # For now, we simulate the live pipeline by calling the API once for the final output.
        prompt = FINAL_OUTPUT_PROMPT.format(
            task=task,
            plan="[Pending Live Plan]",
            findings="[Pending Live Research]",
            result="[Pending Live Execution]",
            verdict="[Pending Live Review]"
        )
        
        llm_response = call_fireworks_api(prompt)
        
        tracer.add_trace("planner", "completed", "Live plan generated.")
        tracer.add_trace("research", "completed", "Live research gathered.")
        tracer.add_trace("executor", "completed", "Live execution finished.")
        tracer.add_trace("reviewer", "completed", "Live review approved.")
        tracer.add_trace("final_report", "completed", "Live report generated by Gemma.")
        
        reviewer_score = {
            "clarity": 90,
            "completeness": 88,
            "actionability": 92,
            "risk": "low",
            "decision": "pass"
        }

        return {
            "task": task,
            "planner_output": {"agent": "planner", "status": "live", "plan": ["AI Plan Generated"]},
            "research_output": {"agent": "researcher", "status": "live", "findings": "AI Research complete"},
            "executor_output": {"agent": "executor", "status": "live", "result": "AI Execution complete"},
            "reviewer_output": {"agent": "reviewer", "status": "live", "approval": True},
            "final_output": llm_response,
            "mode": "live_fireworks",
            "trace": tracer.get_traces(),
            "reviewer_score": reviewer_score
        }
        
    except Exception as e:
        print(f"ERROR: Fireworks API call failed ({e}). Falling back to mock mode.")
        return get_mock_workflow(task, error_mode=True)
