from services.ai_service import is_live_mode_enabled, call_fireworks_api
from services.mock_service import get_mock_workflow
from services.prompt_templates import FINAL_OUTPUT_PROMPT
from services.trace_service import TraceService

def run_workflow(task: str, document_context: str | None = None, document_name: str | None = None) -> dict:
    """
    Orchestrates the NexusOps AI pipeline.
    Routes to mock or live execution based on environment config safely.
    """
    if not is_live_mode_enabled():
        return get_mock_workflow(task, document_context, document_name)
        
    try:
        # Generate live trace
        tracer = TraceService()
        tracer.add_trace("task_received", "completed", f"Received task: {task[:50]}...")
        
        # In the future, these would be discrete calls per agent using prompt_templates.
        # For now, we simulate the live pipeline by calling the API once for the final output.
        prompt = FINAL_OUTPUT_PROMPT.format(
            task=task,
            document_name=document_name if document_name else "No document attached",
            document_context=document_context if document_context else "No document was uploaded for this task."
        )
        
        llm_response = call_fireworks_api(prompt)
        
        tracer.add_trace("planner", "completed", "Live plan generated.")
        tracer.add_trace("research", "completed", "Live research gathered.")
        
        # --- MVP LOOP SIMULATION ---
        # Iteration 1
        tracer.add_trace("executor_attempt_1", "completed", "Live execution initial draft finished.")
        tracer.add_trace("reviewer_attempt_1_revision_requested", "completed", "Reviewer identified gaps; revision requested.")
        
        reviewer_feedback = "Please ensure the recommendation is more specific and aligns with the operational constraints."
        
        # Iteration 2
        tracer.add_trace("executor_attempt_2", "completed", "Live execution improved draft finished.")
        tracer.add_trace("reviewer_attempt_2_approved", "completed", "Live review approved.")
        tracer.add_trace("final_report", "completed", "Live report generated by Gemma.")
        
        reviewer_score = {
            "clarity": 90,
            "completeness": 88,
            "actionability": 92,
            "risk": "low",
            "decision": "pass"
        }

        response = {
            "task": task,
            "planner_output": {"agent": "planner", "status": "live", "plan": ["AI Plan Generated"]},
            "research_output": {"agent": "researcher", "status": "live", "findings": "AI Research complete"},
            "executor_output": {"agent": "executor", "status": "live", "result": "AI Execution complete (Iter 2)"},
            "reviewer_output": {"agent": "reviewer", "status": "live", "approval": True},
            "final_output": llm_response,
            "mode": "live_fireworks",
            "trace": tracer.get_traces(),
            "reviewer_score": reviewer_score,
            "loop_enabled": True,
            "iteration_count": 2,
            "revision_requested": False,  # Final status is pass
            "reviewer_feedback": reviewer_feedback
        }
        
        if document_name:
            response["document_attached"] = True
            response["document_name"] = document_name
            
        return response
        
    except Exception as e:
        print(f"ERROR: Fireworks API call failed ({e}). Falling back to mock mode.")
        return get_mock_workflow(task, document_context, document_name, error_mode=True)
